# Site settings
author: Jimmy Le
title: Jimmy Le
header-img: img/home-bg.png
email: jimmyle414@gmail.com
copyright_name: Jimmy Le
description: > # this means to ignore newlines until "baseurl:"
  Jimmy Le
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jimmyle414

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
